version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db_container
    restart: always
    ports:
      - "5433:5432"  # Redirection du port 5432 du conteneur vers le port 5433 de l'hôte
    environment:
      POSTGRES_USER: cluster
      POSTGRES_PASSWORD: cluster
      POSTGRES_DB: haproxy_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  # Scripts d'initialisation de la base de données
    networks:
      - mynetwork

  codeigniter-app:
    image: php:8.2.12-apache
    container_name: codeigniter_container
    restart: always
    ports:
      - "8080:80"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=haproxy_manager
      - DB_USERNAME=cluster
      - DB_PASSWORD=cluster
    volumes:
      - ./haproxy_manager:/var/www/html
    depends_on:
      - db
    networks:
    - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
